/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universitymanagementsystem;


import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Asus
 */
public class Admission extends javax.swing.JFrame {

    /**
     * Creates new form Admission
     */
    public Admission() {
        initComponents();
       this.setLocationRelativeTo(null);
    }
private void getsection()
{
    section.removeAllItems();
    try{
        Connection con= DriverManager.getConnection(host,username,password);
        Statement stmt= con.createStatement();
        String query="select section from class where class='"+cbclass.getSelectedItem().toString()+"' ";
         ResultSet rs =stmt.executeQuery(query);
         while(rs.next())
         {
             cbsection.addItem(rs.getString("section"));
         }
         
         
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, "Error"+e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamedActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
    }
    private void txtfnamedActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
    }
    private void txtmnamedActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
    }
    private void txtrollActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
    }
    private void txtdobActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
    }
    private void txtadmActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
    }
String host="jdbc:derby://localhost:1527/UniversityManagementSystem";
       String username="university";
       String password="123a";
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt){
        //TODO add your handling code here:
        String gend="";
        if(rbtnma.isSelected())
        {
            gend="Male";
        }
        if(rbtnfem.isSelected())
        {
            gend="Female";
        }
        try{
            connection con = DriverManager.getConnection(host,username,password);
            Statement stmt= con.createStatement();
            String query="insert into student (name,id,intake,section,DOB,gender,mobile,address,fathername,mothername)"
                    + "values('"+txtname.getText()+"','"+txtid.getText()+"','"+cbintake.getSelectedItem().toString()+"','"+section.getSelectedItem().toString()+"','"+txtdob.getText()"','"+gend+"','"+txtfname.getText()+"','"+txtmname.getText()+"','"+txtmobile.getText()"','"+txtaddress.getText()"','"+txtfathername.getText()+"','"+txtmothername.getText()+"')";
                stmt.execute(query);
                    JOptionPane.showMessageDialog(null, "Saved !");
            clear();
                    
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error"+e);
        }
            
    }
    private void cbintakeItemStateChanged(java.awt.event.ItemEvent evt){
        //TODO add your handling code here;
        getsection();
    }
    private void clear()
    {
        txtname.setText(null);
        txtid.setText(null);
        cbintake.setSelectedIndex(1);
        section.removeAllItems();
        txtdob.setText(null);
        txtfname.setText(null);
        
        txtmname.setText(null);
        txtmob.setText(null);
        txtaddress.setText(null);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
